# Generated by Django 4.2.27 on 2026-01-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-cube')", max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tools.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('hero_tagline', models.CharField(blank=True, help_text="e.g., 'AI tools that design faster'", max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tool_logos/')),
                ('website_url', models.URLField()),
                ('affiliate_url', models.URLField(blank=True)),
                ('pricing_type', models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('paid', 'Paid')], default='freemium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='tools', to='tools.category')),
                ('professions', models.ManyToManyField(blank=True, related_name='tools', to='tools.profession')),
                ('tags', models.ManyToManyField(blank=True, related_name='tools', to='tools.tag')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('workflow_description', models.TextField(help_text='Step-by-step how these tools work together')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professions', models.ManyToManyField(blank=True, related_name='stacks', to='tools.profession')),
                ('tools', models.ManyToManyField(related_name='stacks', to='tools.tool')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hu', 'Hungarian'), ('de', 'German')], max_length=2)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField(blank=True)),
                ('use_cases', models.TextField(blank=True, help_text='Comma-separated use cases')),
                ('pros', models.TextField(blank=True, help_text='Comma-separated pros')),
                ('cons', models.TextField(blank=True, help_text='Comma-separated cons')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools.tool')),
            ],
            options={
                'unique_together': {('tool', 'language')},
            },
        ),
    ]
